jobs:
  include:
  - os: linux
    addons:
    apt:
      packages:
        - docker-ce
  - os: linux
    arch: s390x

branches:
  only:
  - travis-s390x

sudo: required

services:
      - docker

before_install:
    - ./contrib/ci.sh

install:
- if [ "$HOSTTYPE" == "s390x" ]; then curl -fsSL https://get.docker.com | bash; fi      
    
script:
    - make

after_success:
    - if [ -z $DOCKER_NS ] ; then
        export DOCKER_NS=openfaas;
        fi
    - if [ ! -z "$TRAVIS_TAG" ] ; then 

        docker tag $DOCKER_NS/faas-swarm:latest-dev $DOCKER_NS/faas-swarm:$TRAVIS_TAG;
        echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin;
        docker push $DOCKER_NS/faas-swarm:$TRAVIS_TAG;

        docker tag $DOCKER_NS/faas-swarm:latest-dev quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;
        echo $QUAY_PASSWORD | docker login -u=$QUAY_USERNAME --password-stdin quay.io;
        docker push quay.io/$DOCKER_NS/faas-swarm:$TRAVIS_TAG;

        fi
        
